# Application Name
spring.application.name=payment-gateway

# Database Configuration 
spring.datasource.url=jdbc:postgresql://localhost:5432/payment_gateway_cip
spring.datasource.username=postgres
spring.datasource.password=fahmi123
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

# Actuator Endpoints
management.endpoint.health.show-details=always
management.endpoints.web.exposure.include=health,info

# Debug
debug=true